name: kfs2d_rna_notebook
channels:
  - conda-forge
dependencies:
  - heapdict
  - gfortran_linux-64
  - libblas
  - liblapack
  - openmpi
  - gnuplot
  - matlab_kernel
  - sos-notebook
  - sos-matlab
  - notebook
